/**
 * SSERuntime - Browser Runtime implementation
 *
 * "Define Once, Run Anywhere"
 *
 * Provides Runtime for browser that connects to remote AgentX server via SSE.
 * Uses the same API as NodeRuntime, enabling unified code across platforms.
 *
 * @example
 * ```typescript
 * import { createAgentX } from "@deepractice-ai/agentx";
 * import { createSSERuntime } from "@deepractice-ai/agentx/client";
 * import { defineAgent } from "@deepractice-ai/agentx";
 *
 * const MyAgent = defineAgent({
 *   name: "Assistant",
 *   systemPrompt: "You are a helpful assistant",
 * });
 *
 * // Browser: connect to remote server
 * const runtime = createSSERuntime({ serverUrl: "http://localhost:5200/agentx" });
 * const agentx = createAgentX(runtime);
 * const agent = agentx.agents.create(MyAgent);
 *
 * // Same API as server-side!
 * agent.on("assistant_message", (event) => {
 *   console.log(event.data.content);
 * });
 *
 * await agent.receive("Hello!");
 * ```
 */

import type {
  Runtime,
  Container,
  Sandbox,
  RuntimeDriver,
  AgentContext,
  AgentDefinition,
  Agent,
  Repository,
} from "@deepractice-ai/agentx-types";
import { createSSEDriver } from "./SSEDriver";
import { RemoteRepository } from "../repository";

// ============================================================================
// MemoryContainer - Simple in-memory container for browser
// ============================================================================

class MemoryContainer implements Container {
  readonly id: string;
  private readonly agents = new Map<string, Agent>();

  constructor(id: string = "sse-container") {
    this.id = id;
  }

  register(agent: Agent): void {
    this.agents.set(agent.agentId, agent);
  }

  get(agentId: string): Agent | undefined {
    return this.agents.get(agentId);
  }

  has(agentId: string): boolean {
    return this.agents.has(agentId);
  }

  unregister(agentId: string): boolean {
    return this.agents.delete(agentId);
  }

  getAllIds(): string[] {
    return Array.from(this.agents.keys());
  }

  count(): number {
    return this.agents.size;
  }

  clear(): void {
    this.agents.clear();
  }
}

// ============================================================================
// NoopSandbox - Browser doesn't need local resources
// ============================================================================

const noopSandbox: Sandbox = {
  name: "browser-noop",
  os: {
    name: "noop",
    fs: null as any,
    process: null as any,
    env: null as any,
    disk: null as any,
  },
  llm: {
    name: "noop",
    provide: () => ({}),
  },
};

// ============================================================================
// SSERuntime - Browser Runtime implementation
// ============================================================================

/**
 * SSERuntime configuration
 */
export interface SSERuntimeConfig {
  /**
   * Server base URL (e.g., "http://localhost:5200/agentx")
   */
  serverUrl: string;

  /**
   * Optional request headers (for auth, etc.)
   */
  headers?: Record<string, string>;

  /**
   * Connect to an existing agent on the server (optional)
   *
   * If provided, SSEDriver will use this agentId instead of the one
   * generated by AgentManager. This is useful when:
   * - Server creates the agent and returns agentId
   * - Browser needs to connect to that existing agent
   */
  agentId?: string;
}

/**
 * SSERuntime - Runtime for browser with SSE driver
 *
 * Connects to remote AgentX server via SSE.
 * All resources (LLM, etc.) are provided by the server.
 */
class SSERuntime implements Runtime {
  readonly name = "sse";
  readonly container: Container;
  readonly repository: Repository;

  private readonly serverUrl: string;
  private readonly headers: Record<string, string>;
  private readonly existingAgentId?: string;

  constructor(config: SSERuntimeConfig) {
    this.serverUrl = config.serverUrl.replace(/\/+$/, ""); // Remove trailing slash
    this.headers = config.headers ?? {};
    this.existingAgentId = config.agentId;
    this.container = new MemoryContainer();
    this.repository = new RemoteRepository({ serverUrl: this.serverUrl });
  }

  createSandbox(_name: string): Sandbox {
    // Browser doesn't need local resources
    return noopSandbox;
  }

  createDriver(
    _definition: AgentDefinition,
    context: AgentContext,
    _sandbox: Sandbox
  ): RuntimeDriver {
    // Use existing agentId if provided, otherwise use the one from context
    const agentId = this.existingAgentId ?? context.agentId;

    // Create SSE driver that connects to remote server
    const driver = createSSEDriver({
      serverUrl: this.serverUrl,
      agentId,
      headers: this.headers,
    });

    // SSEDriver implements AgentDriver, wrap it as RuntimeDriver
    return {
      ...driver,
      sandbox: noopSandbox,
    };
  }
}

// ============================================================================
// Factory function
// ============================================================================

/**
 * Create SSE Runtime for browser
 *
 * @example
 * ```typescript
 * import { createAgentX } from "@deepractice-ai/agentx";
 * import { createSSERuntime } from "@deepractice-ai/agentx/client";
 *
 * const runtime = createSSERuntime({ serverUrl: "http://localhost:5200/agentx" });
 * const agentx = createAgentX(runtime);
 * const agent = agentx.agents.create(MyAgent);
 * ```
 */
export function createSSERuntime(config: SSERuntimeConfig): Runtime {
  return new SSERuntime(config);
}

// Also export class for advanced use
export { SSERuntime };
