/**
 * EnvironmentEvent - All events perceived from external world
 *
 * Architecture:
 * ```
 * EnvironmentEvent (all external perceptions, with requestId)
 * │
 * ├── DriveableEvent (can drive Agent)
 * │   │   - Receptor outputs this (with requestId)
 * │   │   - Driver transforms to AgentStreamEvent (adds agentId)
 * │   └── MessageStartEvent, TextDeltaEvent, ToolCallEvent...
 * │
 * └── ConnectionEvent (network status only, does not drive Agent)
 *     └── ConnectedEvent, DisconnectedEvent, ReconnectingEvent
 * ```
 *
 * Key Design:
 * - All EnvironmentEvents have requestId for routing
 * - requestId links events to the originating request
 * - Driver uses requestId to filter events for its Agent
 *
 * Isomorphic Design:
 * - Same event types work in both NodeEcosystem and RemoteEcosystem
 * - In NodeEcosystem: ClaudeReceptor emits DriveableEvents
 * - In RemoteEcosystem: NetworkReceptor receives events via WebSocket
 */

import type { SystemEvent } from "../base";
import type { DriveableEvent } from "./DriveableEvent";
import type { ConnectionEvent } from "./ConnectionEvent";

/**
 * BaseEnvironmentEvent - Common structure for all environment events
 *
 * All environment events include requestId for routing to the correct Agent/Driver.
 */
export interface BaseEnvironmentEvent<T extends string = string, D = unknown>
  extends SystemEvent<T, D> {
  /**
   * Request ID for routing events to the correct Agent
   *
   * Generated by Agent when sending a request, included in all response events.
   * Driver uses this to filter events that belong to its Agent.
   */
  readonly requestId: string;
}

/**
 * EnvironmentEvent - Union of all external world events
 */
export type EnvironmentEvent = DriveableEvent | ConnectionEvent;

/**
 * Type guard: is this event driveable (can drive Agent)?
 */
export function isDriveableEvent(event: EnvironmentEvent): event is DriveableEvent {
  const connectionTypes = ["connected", "disconnected", "reconnecting"];
  return !connectionTypes.includes(event.type);
}

/**
 * Type guard: is this a connection event?
 */
export function isConnectionEvent(event: EnvironmentEvent): event is ConnectionEvent {
  const connectionTypes = ["connected", "disconnected", "reconnecting"];
  return connectionTypes.includes(event.type);
}
